apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cfg
  namespace: default
data:
  key1: value1
  key2: value2
  my.cnf: |
    [mysqld]
    log-bin = mysql-bin
  app.properties: |
    property.1 = value-1