apiVersion: v1
kind: Pod
metadata:
  name: demo
  labels:
    app: demo
spec:
  restartPolicy: Never
  containers:
    - name: nginx-container
      image: nginx
      ports:
      - name: "http-server"
        containerPort: 80
        hostPort: 80
    