apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rbd-web
spec:
  serviceName: "nginx" # 唯一和deployment的区别处
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.9.1
        ports:
        - name: web
          containerPort: 80
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: 1Gi