apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution: # 每次调度的时候予以考虑
        nodeSelectorTerms:
        - matchExpression:
          - key: metadata.name
            operator: In
            values:
            - node-geektime # 这个 Pod，将来只允许运行在“metadata.name”是“node-geektime”的节点上