apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: pi
        image: busybox
        command:
        - sh
        - "-c"
        - |
          echo "hello"   
  backoffLimit: 4
  activeDeadlineSeconds: 100