// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package message

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReqNil struct {
	Req                  int32    `protobuf:"varint,1,opt,name=req,proto3" json:"req,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqNil) Reset()         { *m = ReqNil{} }
func (m *ReqNil) String() string { return proto.CompactTextString(m) }
func (*ReqNil) ProtoMessage()    {}
func (*ReqNil) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *ReqNil) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqNil.Unmarshal(m, b)
}
func (m *ReqNil) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqNil.Marshal(b, m, deterministic)
}
func (m *ReqNil) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqNil.Merge(m, src)
}
func (m *ReqNil) XXX_Size() int {
	return xxx_messageInfo_ReqNil.Size(m)
}
func (m *ReqNil) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqNil.DiscardUnknown(m)
}

var xxx_messageInfo_ReqNil proto.InternalMessageInfo

func (m *ReqNil) GetReq() int32 {
	if m != nil {
		return m.Req
	}
	return 0
}

type RespNil struct {
	Resp                 int32    `protobuf:"varint,1,opt,name=resp,proto3" json:"resp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespNil) Reset()         { *m = RespNil{} }
func (m *RespNil) String() string { return proto.CompactTextString(m) }
func (*RespNil) ProtoMessage()    {}
func (*RespNil) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *RespNil) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespNil.Unmarshal(m, b)
}
func (m *RespNil) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespNil.Marshal(b, m, deterministic)
}
func (m *RespNil) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespNil.Merge(m, src)
}
func (m *RespNil) XXX_Size() int {
	return xxx_messageInfo_RespNil.Size(m)
}
func (m *RespNil) XXX_DiscardUnknown() {
	xxx_messageInfo_RespNil.DiscardUnknown(m)
}

var xxx_messageInfo_RespNil proto.InternalMessageInfo

func (m *RespNil) GetResp() int32 {
	if m != nil {
		return m.Resp
	}
	return 0
}

func init() {
	proto.RegisterType((*ReqNil)(nil), "message.reqNil")
	proto.RegisterType((*RespNil)(nil), "message.respNil")
}

func init() {
	proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd)
}

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 133 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0xa4, 0xb8,
	0xd8, 0x8a, 0x52, 0x0b, 0xfd, 0x32, 0x73, 0x84, 0x04, 0xb8, 0x98, 0x8b, 0x52, 0x0b, 0x25, 0x18,
	0x15, 0x18, 0x35, 0x58, 0x83, 0x40, 0x4c, 0x25, 0x59, 0x2e, 0xf6, 0xa2, 0xd4, 0xe2, 0x02, 0x90,
	0xa4, 0x10, 0x17, 0x0b, 0x88, 0x09, 0x95, 0x05, 0xb3, 0x8d, 0x6c, 0xb9, 0xb8, 0x1d, 0x4b, 0x4b,
	0x32, 0x82, 0x53, 0x8b, 0xca, 0x32, 0x93, 0x53, 0x85, 0xf4, 0xb8, 0x38, 0x9d, 0x33, 0xb2, 0x3d,
	0x52, 0x13, 0x73, 0x4a, 0x32, 0x84, 0xf8, 0xf5, 0x60, 0xf6, 0x41, 0x4c, 0x97, 0x12, 0x40, 0x12,
	0x00, 0x1b, 0x99, 0xc4, 0x06, 0x76, 0x89, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x9f, 0x95, 0x44,
	0x84, 0x9a, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthServiceClient interface {
	ChkHealth(ctx context.Context, in *ReqNil, opts ...grpc.CallOption) (*RespNil, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) ChkHealth(ctx context.Context, in *ReqNil, opts ...grpc.CallOption) (*RespNil, error) {
	out := new(RespNil)
	err := c.cc.Invoke(ctx, "/message.AuthService/ChkHealth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
type AuthServiceServer interface {
	ChkHealth(context.Context, *ReqNil) (*RespNil, error)
}

// UnimplementedAuthServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (*UnimplementedAuthServiceServer) ChkHealth(ctx context.Context, req *ReqNil) (*RespNil, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChkHealth not implemented")
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}

func _AuthService_ChkHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqNil)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ChkHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.AuthService/ChkHealth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ChkHealth(ctx, req.(*ReqNil))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "message.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ChkHealth",
			Handler:    _AuthService_ChkHealth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}
