apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: demo
  namespace: kube-system
  labels:
    k8s-app: demo
spec:
  selector:
    matchLabels:
      name: demo
  template:
    metadata:
      labels:
        name: demo
    spec:
      tolerations:
      - key: node-role.kubernetest.io/master
        effect: NoSchedule
      containers:
      - name: demo
        image: nginx
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
        - name: "demo-nginx"
          containerPort: 80

      
    
