apiVersion: v1
kind: Pod
metadata:
  name: clientset-demo
  labels:
    app: clientset-demo
spec:
  nodeSelector:
    kubernetes.io/hostname: master
  containers:
    - name: cn0
      image: registry.cn-hangzhou.aliyuncs.com/customs/goclient-demo:latest
      imagePullPolicy: IfNotPresent
      args:
        - "--kubeconfig ./kube/config"