apiVersion: apps/v1
kind: Deployment
metadata:
    name: demo
    namespace: kube-test
    labels:
        app: demo
spec:
    selector:
        matchLabels:
            app: demo
    template:
        metadata:
            name: demo
        spec:
            containers:
            - name: cn0
              image: nginx
                   
             